version: "3.9"

services:
  kong-db:
    image: postgres:13-bullseye
    container_name: postgres_db
    restart: on-failure
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    ports:
      - 5413:5432
    volumes:
      - kong-volume:/var/lib/postgresql/data
    networks:
      - kong-net
  
  kong-migrations:
    image: kong:3.7-ubuntu
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PORT=5432
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    networks:
      - kong-net
  
  kong-apigw:
    image: kong:3.7-ubuntu
    container_name: kong-apigw
    restart: always
    networks:
      - kong-net
    depends_on:
      - kong-migrations
      - kong-db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444

networks:
  kong-net:

volumes:
  kong-volume: