version: "3.8"

services:
    postgres:
        image: postgres:16.8
        container_name: postgres16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

volumes:
    postgres_data:
