
version: '3.8'

services:
  postgres:
    image: postgres:16.8
    container_name: postgres
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: