version: '3.1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--bind_ip_all"]
    ports:
      - 27027:27017
    networks:
      - mongo_network
    volumes:
      - "mongo_data:/data/db"
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      - mongodb
    networks:
      - mongo_network
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo_data:

networks:
    mongo_network:
      driver: bridge