services:
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      apisix:

  apisix:
    image: apache/apisix:3.11.0-debian
    container_name: apisix
    restart: always
    volumes:
      - ./conf/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
      # Mount Let's Encrypt SSL certificates from host
      - /etc/letsencrypt/live/apptronium.com/fullchain.pem:/etc/letsencrypt/live/apptronium.com/fullchain.pem:ro
      - /etc/letsencrypt/live/apptronium.com/privkey.pem:/etc/letsencrypt/live/apptronium.com/privkey.pem:ro
    depends_on:
      - etcd
    ports:
      - "80:9080"
      - "443:9443"
      - "9180:9180"
    networks:
      apisix:

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ./conf/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "8384:9000"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
