version: '3.8'

services:
  jenkins-blueocean:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sw-jenkins:1.0.1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - docker

  docker:
    image: docker:dind
    networks:
      - jenkins
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
