version: "3.8"

services:
  service-one:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - apptronium_net

networks:
  apptronium_net:
    external: true
