version: '3.8'
services:
  postgres14:
    image: postgres:14-bullseye
    container_name: postgres14
    ports:
      - 5414:5432
    volumes:
      - postgres14_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=progoti
      - POSTGRES_PASSWORD=Pr0g0ti
      - POSTGRES_DB=tallykhata_log

volumes:
  postgres14_data:
