version: '3.8'
services:
  postgres:
    image: postgres:14-bookworm
    container_name: pg14
    ports:
      - 5454:5432
    volumes:
      - pg14_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin

volumes:
  pg14_data:
