version: '3.8'
services:
  postgres:
    image: postgres:14-bookworm
    container_name: pg14
    ports:
      - 5454:5432
    volumes:
      - pg14_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=progoti
      - POSTGRES_PASSWORD=Pr0g0ti
      - POSTGRES_DB=tallykhata_log

volumes:
  pg14_data:
