version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - 5454:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - 8054:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=salman@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  timescaledb_data:
