version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - 5454:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=progoti
      - POSTGRES_PASSWORD=Pr0g0ti
      - POSTGRES_DB=tallykhata_log

volumes:
  timescaledb_data:
 
