version: "3.8"

services:
    redis:
        image: redis:6.2
        container_name: redis_server
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
    redis_data:
